@startuml
(*) --> "レストランで気になるメニューを注文する"
"レストランで気になるメニューを注文する" --> "食べる"
if "感想" then
  --> [美味しい] "レシピを調べる"
  --> "材料を買ってくる"
  --> "料理する"
else
  --> [美味しくない] "とりあえず食べる"
  --> "レストランで気になるメニューを注文する"
@enduml